# Generated by Django 5.2.6 on 2025-10-05 20:01

import ckeditor.fields
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacansiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Keywords')),
            ],
            options={
                'verbose_name': 'Vacansiya',
                'verbose_name_plural': 'Vacansiyalar',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VacansiyaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacansiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vacansiya.vacansiya', verbose_name='Asosiy Vacansiya')),
            ],
            options={
                'verbose_name': 'Vacansiya item',
                'verbose_name_plural': 'Vacansiya itemlar',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VacansiyaItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('position', models.CharField(max_length=255, verbose_name='Lavozim nomi')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vacansiya.vacansiyaitem')),
            ],
            options={
                'verbose_name': 'Vacansiya item Translation',
                'db_table': 'vacansiya_vacansiyaitem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VacansiyaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Сарлавха')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Контент')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vacansiya.vacansiya')),
            ],
            options={
                'verbose_name': 'Vacansiya Translation',
                'db_table': 'vacansiya_vacansiya_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
