# Generated by Django 5.2.6 on 2025-10-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_homeseo_homeseotranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeseotranslation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
