# Generated by Django 5.2.6 on 2025-09-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_aboutmainimage_hitofsales_alter_aboutimages_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='colorbutton',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Button Color'),
        ),
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
