# Generated by Django 5.2.6 on 2025-09-25 18:26

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_banner_colorbutton_banner_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='colorbutton',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
