# Generated by Django 5.2.6 on 2025-09-25 18:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_banner_colorbutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='backgrouncolor',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
