# Generated by Django 5.2.6 on 2025-09-28 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_bannerhome_bannerhometranslation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Slider', 'verbose_name_plural': 'Sliderlar'},
        ),
        migrations.AlterModelOptions(
            name='bannerhome',
            options={'verbose_name': 'Banner ', 'verbose_name_plural': 'Banner'},
        ),
        migrations.AlterModelOptions(
            name='bannerhometranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Banner  Translation'},
        ),
        migrations.AlterModelOptions(
            name='bannertranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Slider Translation'},
        ),
        migrations.RemoveField(
            model_name='clients',
            name='url',
        ),
        migrations.DeleteModel(
            name='ClientsTranslation',
        ),
    ]
