# Generated by Django 5.2.6 on 2025-09-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_rename_metadetails_metadetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoriya', 'verbose_name_plural': 'Categorialar'},
        ),
        migrations.AlterModelOptions(
            name='categorytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Categoriya Translation'},
        ),
    ]
