# Generated by Django 5.2.6 on 2025-09-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
