# Generated by Django 5.2.6 on 2025-09-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_is_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Ommabop kategoriya'),
        ),
    ]
