# Generated by Django 5.2.6 on 2025-10-05 20:01

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footeraddres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('logo', models.ImageField(upload_to='payments/', verbose_name='Rasm')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Toʻlov ssilkasi')),
            ],
            options={
                'verbose_name': 'Toʻlov usuli',
                'verbose_name_plural': 'Toʻlov usullari',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255, verbose_name='Сайт номи')),
                ('logo', models.FileField(blank=True, null=True, upload_to='logos/', verbose_name='Лого (SVG ёки PNG)')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Телефон рақами')),
            ],
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('link', models.URLField(verbose_name='Havola')),
                ('classlink', models.CharField(max_length=200, verbose_name='CSS klassi')),
            ],
            options={
                'verbose_name': 'Social tarmoq',
                'verbose_name_plural': 'Social tarmoqlar',
            },
        ),
        migrations.CreateModel(
            name='FooteraddresTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('address', models.CharField(max_length=200, verbose_name='Korxona manzili')),
                ('telefon', models.CharField(max_length=200, verbose_name='Telefon raqami')),
                ('email', models.CharField(max_length=200, verbose_name='Email manzili')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='site_settings.footeraddres')),
            ],
            options={
                'verbose_name': 'footeraddres Translation',
                'db_table': 'site_settings_footeraddres_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
