# Generated by Django 5.2.6 on 2025-09-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255, verbose_name='Сайт номи')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Лого')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Телефон рақами')),
            ],
        ),
    ]
