# Generated by Django 5.2.6 on 2025-09-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logos/', verbose_name='Лого (SVG ёки PNG)'),
        ),
    ]
