# Generated by Django 5.2.6 on 2025-09-28 08:14

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alter_sitesettings_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footeraddres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FooteraddresTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('address', models.CharField(max_length=200, verbose_name='Korxona manzili')),
                ('telefon', models.CharField(max_length=200, verbose_name='Telefon raqami')),
                ('email', models.CharField(max_length=200, verbose_name='Email manzili')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='site_settings.footeraddres')),
            ],
            options={
                'verbose_name': 'footeraddres Translation',
                'db_table': 'site_settings_footeraddres_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
