# Generated by Django 5.2.6 on 2025-09-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_footeraddres_footeraddrestranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('link', models.URLField(verbose_name='Havola')),
                ('classlink', models.CharField(max_length=200, verbose_name='CSS klassi')),
            ],
            options={
                'verbose_name': 'Social tarmoq',
                'verbose_name_plural': 'Social tarmoqlar',
            },
        ),
    ]
