# Generated by Django 5.2.6 on 2025-09-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_socials'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('logo', models.ImageField(upload_to='payments/', verbose_name='Rasm')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Toʻlov ssilkasi')),
            ],
            options={
                'verbose_name': 'Toʻlov usuli',
                'verbose_name_plural': 'Toʻlov usullari',
            },
        ),
    ]
