# Generated by Django 5.2.6 on 2025-10-09 11:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta',
            options={'verbose_name': 'Oferta', 'verbose_name_plural': 'Ofertas'},
        ),
        migrations.AlterModelOptions(
            name='ofertatranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Oferta Translation'},
        ),
        migrations.AlterField(
            model_name='ofertatranslation',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
    ]
