# Generated by Django 5.2.6 on 2025-10-10 06:47

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_slug'),
    ]

    operations = [
    # 1️⃣ Avvalo rename
    migrations.RenameModel(
        old_name='ProductAttributeValueTranslation',
        new_name='AttributeValueTranslation',
    ),
    
    # 2️⃣ Keyin model options va table
    migrations.AlterModelOptions(
        name='attributevaluetranslation',
        options={'default_permissions': (), 'managed': True, 'verbose_name': 'attribute value Translation'},
    ),
    migrations.AlterModelTable(
        name='attributevaluetranslation',
        table='store_attributevalue_translation',
    ),
    
    # 3️⃣ Boshqa o‘zgartirishlar
    migrations.AlterModelOptions(
        name='product',
        options={},
    ),
    migrations.AlterModelOptions(
        name='producttranslation',
        options={'default_permissions': (), 'managed': True, 'verbose_name': 'product Translation'},
    ),
    migrations.RemoveField(
        model_name='product',
        name='download',
    ),
    migrations.RemoveField(
        model_name='product',
        name='modified_date',
    ),
    migrations.RemoveField(
        model_name='product',
        name='new',
    ),
    migrations.RemoveField(
        model_name='product',
        name='top',
    ),
    migrations.RemoveField(
        model_name='product',
        name='v_nalichi',
    ),
    migrations.AlterField(
        model_name='attribute',
        name='slug',
        field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug'),
    ),
    migrations.AlterField(
        model_name='product',
        name='created_date',
        field=models.DateTimeField(auto_now_add=True),
    ),
    migrations.AlterField(
        model_name='product',
        name='is_available',
        field=models.BooleanField(default=True, verbose_name='Available'),
    ),
    migrations.CreateModel(
        name='AttributeValue',
        fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='store.attribute')),
        ],
        options={
            'abstract': False,
        },
        bases=(parler.models.TranslatableModelMixin, models.Model),
    ),
    migrations.AddField(
        model_name='product',
        name='atribut_values',
        field=models.ManyToManyField(blank=True, related_name='products', to='store.attributevalue', verbose_name='Attribute Values'),
    ),
    migrations.AlterField(
        model_name='attributevaluetranslation',
        name='master',
        field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='store.attributevalue'),
    ),
    migrations.DeleteModel(
        name='ProductAttributeValue',
    ),
]

