"""
Django settings for energy project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=a&p7kdi=22!uubkx55_2lundh#0q^+&i*mn45ox$58g+iimnn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'store',
    'vacansiya',
    'faq',
    'conatact',
    'about',
    'news',
    'colorfield',
   'adminlte3',
    'adminlte3_theme',    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',    
    'category',
    'mptt',
    'parler',    
    'rosetta',
    'carts',
    'pages',
    'ckeditor',
    'ckeditor_uploader',
   'site_settings',
   'oferta',
   'dal',
   'dal_select2',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'energy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'site_settings.context_processors.site_settings', 
                'site_settings.context_processors.latest_categories', 
                'site_settings.context_processors.footeraddres',
                'site_settings.context_processors.socials',
                'site_settings.context_processors.paymentmethod', 
                'site_settings.context_processors.footercategory',
                'site_settings.context_processors.menuall',
                'site_settings.context_processors.breadcrumbs',
                'site_settings.context_processors.wishlist_count',  
                  
                 
                

                 
                               
                               # Context for category
                'category.context_processors.menu_links',
                'category.context_processors.meta_word',
                'category.context_processors.hit_sale',
                'carts.context_processors.counter',
            ],
            'libraries': {
                'current_lang': 'energy.templatetags.current_lang',
                'reverse_lang': 'energy.templatetags.reverse_lang',
            }
        },
    },
]

WSGI_APPLICATION = 'energy.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# STATIC
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",  # o‘zing qo‘yadigan css/js shu yerda bo‘lsin
]
STATIC_ROOT = BASE_DIR / "staticfiles"  # collectstatic natijasi (prod-da kerak bo‘ladi)

# MEDIA
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# CKEDITOR
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_FILENAME_GENERATOR = 'utils.get_filename'
# yes  <-- bu satrni o'chiring yoki izohga oling

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
    },
}



# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Parler
LANGUAGES = [
    ('ru', "Ru"),
    ('uz', "Uz"),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale')
]

PARLER_LANGUAGES = {
    None: (
        {'code': 'ru', },
        {'code': 'uz', },
    ),
    'default': {
        'fallbacks': ['ru'],  # defaults to PARLER_DEFAULT_LANGUAGE_CODE
        'hide_untranslated': False,  # the default; let .active_translations() return fallbacks too.
    }
}

PARLER_DEFAULT_LANGUAGE_CODE = 'ru'

PARLER_ENABLE_CACHING = False

CSRF_TRUSTED_ORIGINS = ['https://energopribor.uz',
                         "https://ferromagnetic-unappealably-amani.ngrok-free.dev", ]

# Rosetta
ROSETTA_STORAGE_CLASS = 'rosetta.storage.CacheRosettaStorage'

# ROSETTA_ACCESS_CONTROL_FUNCTION = "energy.settings.has_rosetta_access"


# EMAIL

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'testenergopribor@gmail.com'
EMAIL_HOST_PASSWORD = 'uzinouzi123'
DEFAULT_TO_EMAIL = '2482003@energopribor.uz'
