# Generated by Django 5.2.6 on 2025-09-28 12:41

import ckeditor.fields
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Расм')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Title')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Keywords')),
            ],
            options={
                'verbose_name': 'Янгилик',
                'verbose_name_plural': 'Янгиликлар',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NewsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Сарлавҳа')),
                ('description', models.TextField(verbose_name='Қисқача матн')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Контент')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news.news')),
            ],
            options={
                'verbose_name': 'Янгилик Translation',
                'db_table': 'news_news_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
